name: flutter_pretty_dio_logger
description: Show the correct json format, cUrl, easy to copy and use for many purposes.
version: 3.0.0
homepage: https://github.com/CuongNV12/flutter_pretty_dio_logger

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  dio: ^5.0.0

dev_dependencies:
  flutter_lints: ^2.0.1
  test: ^1.21.4
